import { NavItem } from "src/app/models/nav-item";
import { Role } from "src/app/models/role";

export const navItems: NavItem[] = 
    [
        {
          path: "",
          title: "MENUITEMS.MAIN.TEXT",
          iconType: "",
          icon: "",
          class: "",
          groupTitle: true,
          badge: "",
          badgeClass: "",
          role: ["All"],
          isExpanded: false,
          items: [],
        },
      
        // Doctor Modules
        {
          path: "/doctor/dashboard",
          title: "Dashboard",
          iconType: "material-icons-two-tone",
          icon: "space_dashboard",
          class: "",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: [Role.hcp],
          isExpanded: false,
          items: [{
            path: "/authentication/signin",
            title: "Sign In",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            isExpanded: false,
            items: [],
          },
          {
            path: "/authentication/signup",
            title: "Sign Up",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            isExpanded: false,
            items: [{
              path: "/authentication/forgot-password",
              title: "Forgot Password",
              iconType: "",
              icon: "",
              class: "ml-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [],
            },
            {
              path: "/authentication/locked",
              title: "Locked",
              iconType: "",
              icon: "",
              class: "ml-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [],
            }],
          }],
        },
      
        // Patient Modules
        {
          path: "/patient/dashboard",
          title: "MENUITEMS.DASHBOARD.LIST.PATIENT-DASHBOARD",
          iconType: "material-icons-two-tone",
          icon: "space_dashboard",
          class: "",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: ["Patient"],
          isExpanded: false,
          items: [],
        },
        // Common Modules
      
        {
          path: "",
          title: "Authentication",
          iconType: "material-icons-two-tone",
          icon: "supervised_user_circle",
          class: "menu-toggle",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: ["Admin"],
          isExpanded: false,
          items: [
            {
              path: "/authentication/signin",
              title: "Sign In",
              iconType: "",
              icon: "",
              class: "ml-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [],
            },
            {
              path: "/authentication/signup",
              title: "Sign Up",
              iconType: "",
              icon: "",
              class: "ml-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [],
            },
            {
              path: "/authentication/forgot-password",
              title: "Forgot Password",
              iconType: "",
              icon: "",
              class: "ml-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [],
            },
            {
              path: "/authentication/locked",
              title: "Locked",
              iconType: "",
              icon: "",
              class: "ml-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [],
            },
            {
              path: "/authentication/page404",
              title: "404 - Not Found",
              iconType: "",
              icon: "",
              class: "ml-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [],
            },
            {
              path: "/authentication/page500",
              title: "500 - Server Error",
              iconType: "",
              icon: "",
              class: "ml-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [],
            },
          ],
        },
        {
          path: "",
          title: "Extra Pages",
          iconType: "material-icons-two-tone",
          icon: "description",
          class: "menu-toggle",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: ["Admin"],
          isExpanded: false,
          items: [
            {
              path: "/extra-pages/blank",
              title: "Blank Page",
              iconType: "",
              icon: "",
              class: "ml-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [],
            },
          ],
        },
        {
          path: "",
          title: "Multi level Menu",
          iconType: "material-icons-two-tone",
          icon: "slideshow",
          class: "menu-toggle",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: ["Admin"],
          isExpanded: false,
          items: [
            {
              path: "/multilevel/first1",
              title: "First",
              iconType: "",
              icon: "",
              class: "ml-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [],
            },
            {
              path: "/",
              title: "Second",
              iconType: "",
              icon: "",
              class: "ml-sub-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [
                {
                  path: "/multilevel/secondlevel/second1",
                  title: "Second 1",
                  iconType: "",
                  icon: "",
                  class: "ml-menu2",
                  groupTitle: false,
                  badge: "",
                  badgeClass: "",
                  role: [""],
                  isExpanded: false,
                  items: [],
                },
                {
                  path: "/",
                  title: "Second 2",
                  iconType: "",
                  icon: "",
                  class: "ml-sub-menu2",
                  groupTitle: false,
                  badge: "",
                  badgeClass: "",
                  role: [""],
                  isExpanded: false,
                  items: [
                    {
                      path: "/multilevel/thirdlevel/third1",
                      title: "third 1",
                      iconType: "",
                      icon: "",
                      class: "ml-menu3",
                      groupTitle: false,
                      badge: "",
                      badgeClass: "",
                      role: [""],
                      isExpanded: false,
                      items: [],
                    },
                  ],
                },
              ],
            },
            {
              path: "/multilevel/first3",
              title: "Third",
              iconType: "",
              icon: "",
              class: "ml-menu",
              groupTitle: false,
              badge: "",
              badgeClass: "",
              role: [""],
              isExpanded: false,
              items: [],
            },
          ],
        },
      ];